# PATHS
train_dataset: ./data/train
validation_dataset: ./data/eval
#predict_dataset:
load_model_path: ./CheckPoint/experiment_2021_10_15_16_53_48/ckpt/weights.02-0.207
additional_functions_file: ./main.py
output_path: ./

# OPTIMIZATION OPTIONS
loss: BinaryCrossentropy
optimizer:
  type: Adam
  learning_rate:  # define a schedule
    type: ExponentialDecay
    initial_learning_rate: 0.0005
    decay_steps: 80000
    decay_rate: 0.6
metrics: [BinaryAccuracy]

# TRAINING OPTIONS
batch_size: 1
epochs: 1000
epoch_size: 1000
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 100
val_frequency: 1
