# PATHS
train_dataset: ./data/train
validation_dataset: ./data/validation
predict_dataset: ./data/test
#load_model_path: ./CheckPoint/<path_to_hdf5_file>
output_path: ./

# OPTIMIZATION OPTIONS
loss: BinaryCrossentropy
optimizer:
  type: Adam
  learning_rate:  0.001
metrics: [BinaryAccuracy, Precision, Recall]

# TRAINING OPTIONS
batch_size: 1
epochs: 300
epoch_size: 100
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 100
val_frequency: 1
execute_gpu: False
