# PATHS
train_dataset: ./data/train
validation_dataset: ./data/eval
#predict_dataset:
#load_model_path:
additional_functions_file: ./main.py
output_path: ./examples/Q-size/

# OPTIMIZATION OPTIONS
loss: MeanSquaredError
optimizer:
  type: Adam
  learning_rate:  # define a schedule
    type: ExponentialDecay
    initial_learning_rate: 0.001
    decay_steps: 80000
    decay_rate: 0.6
metrics: [MeanAbsoluteError]

# TRAINING OPTIONS
batch_size: 1
epochs: 3
epoch_size: 1000
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 100
val_frequency: 1
