# PATHS
additional_functions_file: ./main.py
train_dataset: ./data/train_10
validation_dataset: ./data/validation_10
#predict_dataset: ./data/validation_10
#load_model_path: ./CheckPoint/experiment_2021_10_14_15_56_21/ckpt/weights.10--0.87
output_path: ./

# OPTIMIZATION OPTIONS
loss: sum_rate_loss
optimizer:
  type: Adam
  learning_rate: 1.0e-5
metrics: [sum_rate_metric]

# TRAINING OPTIONS
batch_size: 1
epochs: 10
epoch_size: 1000
shuffle_training_set: False
shuffle_validation_set: False
val_samples: 100
val_frequency: 1
