# PATHS
train_dataset: ./data/train
validation_dataset: ./data/eval
#predict_dataset: ./gbnMigrated/eval
#load_model_path: ./CheckPoint/experiment_2021_10_07_16_22_30/ckpt/weights.37-0.00.hdf5
additional_functions_file: ./main.py
output_path: ./

# OPTIMIZATION OPTIONS
loss: MeanSquaredError
optimizer:
  type: Adam
metrics: [MeanAbsoluteError]

# TRAINING OPTIONS
batch_size: 16
epochs: 100
epoch_size: 3000
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 1000
val_frequency: 1