name: Upload Documentation

on:
  release:
      types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx-rtd-theme myst-parser
    - name: Build sphinx documentation
      run: |
        sphinx-build -b html docs/ docs/_build/html
    - name: Upload docs
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        server: ignnition.net
        port: 13000
        username: ${{ secrets.SCP_USERNAME }}
        password: ${{ secrets.SCP_PASSWORD }}
        local-dir: docs/_build/html/